### ISSUE TITLE
Move filePreProcessing.ipynb functionality to a script

### ISSUE THREAD

**Issue by ashenfernando1** [mi3nts/interactiveADELE#3]
- [ ] Create a script out of the code blocks on the notebook
- [ ] Ensure it runs!

Let's use 'small' Whisper models as a baseline

**Comment by bmitsevich** [comment]
Hello Ash,
I believe I solved all the dependency issues for running the script locally, however, I'm getting an error with privileges. 
OSError: [WinError 1314] A required privilege is not held by the client: 'C:\\Users\\bmits\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\5c0be3875fda05e81f3c004ed8c7c06be308de1e\\hyperparams.yaml' -> 'C:\\Users\\bmits\\.cache\\torch\\pyannote\\speechbrain\\hyperparams.yaml'.
I am unsure if I need some permissions or if the issues lie elsewhere.

**Comment by ashenfernando1** [comment]
Thanks for the update Benson. Hm, can you try running the script/vscode as admin? Does that work?

https://stackoverflow.com/questions/73782400/oserror-winerror-1314-when-doing-sentiment-analysis-using-flair
