### ISSUE TITLE
Create Docker container with all required libraries precompiled

### ISSUE THREAD

**Issue by ashenfernando1** [mi3nts/interactiveADELE#4]
- Learn about deploying Docker images as containers/environments
- We want to recreate the environment we create through conda, but instead on a docker image that can be loaded and run the dashboard
  - in this manner, we shouldn't have to create the environment using conda or a .yml file
  - instead, we could simply use a requirements file (with no confusion between conda channels and activating environments etc.)
- Data should not be part of the docker image, and would need to be ingested instead

**Comment by MertBuyulu** [comment]
Hey Ash, I have installed docker on my local machine, updated the existing Dockerfile, and successfully created an image called interactive-adele:1.0. However, I'm getting some dependency issues, as I got with the anaconda setup. I will provide more updates later this week

**Comment by peterthoang** [comment]
> Hey Ash, I have installed docker on my local machine, updated the existing Dockerfile, and successfully created an image called interactive-adele:1.0. However, I'm getting some dependency issues, as I got with the anaconda setup. I will provide more updates later this week

Running into similar issues on Windows workstation, image is ~5gb

**Comment by MertBuyulu** [comment]
Update: The docker image is up and running without any problems. However, the data is part of the docker image at the moment. I will work on removing data from the container as well as resolving the dependency and other problems with the preprocessing file

**Comment by ashenfernando1** [comment]
Nice one! Looking forward to hearing the updates on Monday.
